### ISSUE TITLE
Please include a license

### ISSUE THREAD

**Issue by mgorny** [mnorin/kyocera-ppd-installer#2]
I can't find any license notice in the included script files. Given that they are complex to some degree, and certainly copyrightable, it'd be much preferable if you chose a specific license and clearly indicated it. Otherwise, we have to assume 'all rights reserved' which doesn't permit free redistribution/reuse.

**Comment by mnorin** [comment]
Added license text and information about licenses for script itself and binary files. Just to summarize: binary files are distributed under license defined by Kyocera, the installer script itself is distributed under GPLv2
